const btn=document.getElementById("downloadBtn"),btn2=document.getElementById("downloadBtn2"),version=document.getElementById("version"),menu=document.querySelector(".mobile-menu"),menuBtn=document.querySelector(".menu-btn"),nav=document.querySelector(".nav"),progress=document.getElementById("progress"),heroVisual=document.getElementById("heroVisual");
const api="https://api.github.com/repos/mm2vault/VYRA/releases?per_page=30";
fetch(api,{headers:{Accept:"application/vnd.github+json"}}).then(r=>r.ok?r.json():Promise.reject()).then(rs=>{const latest=rs.filter(x=>!x.draft).sort((a,b)=>new Date(b.published_at||b.created_at)-new Date(a.published_at||a.created_at))[0];if(!latest)throw 0;const apk=(latest.assets||[]).find(x=>x.name.toLowerCase().endsWith(".apk"));version.textContent="Son sürüm: "+latest.tag_name+(latest.prerelease?" · prerelease":"");const url=apk?.browser_download_url||latest.html_url;btn.href=url;btn2.href=url}).catch(()=>{version.textContent="En güncel APK GitHub Releases üzerinde.";btn.href=btn2.href="https://github.com/mm2vault/VYRA/releases"});
menuBtn?.addEventListener("click",()=>{const open=menu.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});menu?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{menu.classList.remove("open");menuBtn?.setAttribute("aria-expanded","false")}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;let targetX=innerWidth/2,targetY=innerHeight*.4,currentX=targetX,currentY=targetY;const pointer=()=>{currentX+=(targetX-currentX)*.12;currentY+=(targetY-currentY)*.12;document.documentElement.style.setProperty("--mx",currentX+"px");document.documentElement.style.setProperty("--my",currentY+"px");if(!reduce)requestAnimationFrame(pointer)};if(!reduce&&matchMedia("(pointer:fine)").matches){addEventListener("pointermove",e=>{targetX=e.clientX;targetY=e.clientY},{passive:true});pointer()}
addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?(scrollY/h)*100:0)+"%";nav.classList.toggle("scrolled",scrollY>18)},{passive:true});
if(!reduce&&matchMedia("(pointer:fine)").matches){const phone=heroVisual?.querySelector(".phone");heroVisual?.addEventListener("pointermove",e=>{const r=heroVisual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;if(phone)phone.style.transform="rotate(4deg) rotateY("+(x*10)+"deg) rotateX("+(-y*10)+"deg) translate("+x*5+"px,"+y*5+"px)";heroVisual.querySelectorAll(".tilt-card").forEach((el,i)=>{el.style.transform="translate3d("+(x*(i+1)*8)+"px,"+(y*(i+1)*8)+"px,0)"})},{passive:true});heroVisual?.addEventListener("pointerleave",()=>{if(phone)phone.style.transform="rotate(4deg)";heroVisual.querySelectorAll(".tilt-card").forEach(el=>el.style.transform="")})}
if(!reduce&&matchMedia("(pointer:fine)").matches){document.querySelectorAll(".magnetic").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform="translate("+(x*.08)+"px,"+(y*.08)+"px)"});el.addEventListener("pointerleave",()=>el.style.transform="")});document.querySelectorAll(".feature.tilt-card").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform="perspective(700px) rotateX("+(-y/r.height*5)+"deg) rotateY("+(x/r.width*5)+"deg) translateY(-3px)"});el.addEventListener("pointerleave",()=>el.style.transform="")})}
const canvas=document.getElementById("particles"),ctx=canvas?.getContext("2d");if(canvas&&!reduce){let W=0,H=0,dpr=Math.min(devicePixelRatio||1,2),dots=[];const resize=()=>{W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(dpr,0,0,dpr,0,0);dots=Array.from({length:Math.min(80,Math.floor(W/15))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.5+.3,v:(Math.random()-.5)*.18,a:Math.random()*.5+.15}))};resize();addEventListener("resize",resize);const draw=()=>{ctx.clearRect(0,0,W,H);for(const p of dots){p.y-=.08;p.x+=p.v;if(p.y<-5)p.y=H+5;if(p.x<-5)p.x=W+5;if(p.x>W+5)p.x=-5;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle="rgba(194,108,255,"+p.a+")";ctx.fill()}requestAnimationFrame(draw)};draw()}
const shots=document.querySelectorAll(".shot");shots.forEach(s=>s.addEventListener("click",()=>{s.classList.toggle("focus");if(s.classList.contains("focus")){s.scrollIntoView({behavior:"smooth",block:"center"})}}));
// CINEMATIC VYRA EXPERIENCE
const cinematicStyle=document.createElement("style");
cinematicStyle.textContent=`
#cinematic{max-width:1180px;margin:auto;padding:110px 22px 80px;position:relative}
.cine-head{max-width:700px;margin-bottom:55px}.cine-head span{font-size:10px;letter-spacing:.2em;color:#bba9c9;font-weight:800}.cine-head h2{font-size:clamp(44px,5vw,70px);line-height:.94;letter-spacing:-.055em;margin:17px 0}.cine-head h2 em{font-style:normal;background:linear-gradient(100deg,#fff,#a957ff,#f09bff);-webkit-background-clip:text;color:transparent}.cine-head p{color:#a69caf;line-height:1.75}
.cine-stage{height:680px;border:1px solid #30203d;border-radius:32px;background:radial-gradient(circle at 50% 42%,#8d3cff18,transparent 38%),#08050d;position:relative;overflow:hidden;display:grid;place-items:center;box-shadow:0 40px 100px #0008}.cine-stage:before{content:"";position:absolute;inset:0;background:linear-gradient(transparent 49%,#ffffff05 50%,transparent 51%),linear-gradient(90deg,transparent 49%,#ffffff05 50%,transparent 51%);background-size:100% 90px,90px 100%;opacity:.35}
.cine-phone{position:relative;width:285px;padding:8px;border:1px solid #4a3157;border-radius:38px;background:#05040a;box-shadow:0 45px 100px #000,0 0 80px #8d3cff35;z-index:3;transition:transform .25s ease,opacity .25s}.cine-phone img{width:100%;display:block;aspect-ratio:9/19.5;object-fit:cover;border-radius:30px}.cine-label{position:absolute;z-index:4;top:24px;left:24px;color:#8e7b9b;font-size:8px;letter-spacing:.2em}.cine-step{position:absolute;right:24px;top:24px;color:#b76cff;font-size:9px;letter-spacing:.16em}.cine-caption{position:absolute;bottom:25px;left:25px;right:25px;display:flex;justify-content:space-between;align-items:end;z-index:4}.cine-caption strong{font-size:20px}.cine-caption small{color:#766a80;font-size:9px}.cine-dots{display:flex;gap:5px}.cine-dots i{width:6px;height:6px;border-radius:50%;background:#33243e}.cine-dots i.active{width:22px;border-radius:8px;background:#a957ff;box-shadow:0 0 16px #a957ff}
.cine-orb{position:absolute;width:390px;height:390px;border-radius:50%;background:#8d3cff22;filter:blur(70px);animation:cinePulse 4s ease-in-out infinite}.cine-orb.o2{width:220px;height:220px;background:#ed72ff18;right:5%;top:15%;animation-delay:-2s}.cine-orb.o3{width:180px;height:180px;background:#6335ff18;left:8%;bottom:10%;animation-delay:-1s}@keyframes cinePulse{50%{transform:scale(1.15);opacity:.65}}
.cine-controls{position:absolute;left:25px;bottom:25px;display:flex;gap:8px;z-index:5}.cine-controls button{border:1px solid #352441;background:#0d0814d9;color:#fff;border-radius:11px;padding:9px 12px;font-size:9px;cursor:pointer}.cine-controls button:hover{border-color:#8d3cff}
.cine-steps{display:flex;justify-content:center;gap:10px;margin-top:16px}.cine-steps button{width:9px;height:9px;padding:0;border:0;border-radius:50%;background:#382643;cursor:pointer}.cine-steps button.active{width:28px;border-radius:8px;background:#a957ff}
#lightbox{position:fixed;inset:0;z-index:200;background:#030106eF;backdrop-filter:blur(20px);display:grid;place-items:center;opacity:0;pointer-events:none;transition:.25s;padding:20px}#lightbox.open{opacity:1;pointer-events:auto}#lightbox img{max-width:min(92vw,700px);max-height:88vh;border-radius:24px;border:1px solid #513566;box-shadow:0 40px 100px #000}#lightbox button{position:absolute;top:22px;right:22px;width:44px;height:44px;border:1px solid #493052;border-radius:50%;background:#100a18;color:#fff;font-size:22px;cursor:pointer}
@media(max-width:620px){#cinematic{padding:70px 17px}.cine-stage{height:590px;border-radius:23px}.cine-phone{width:230px}.cine-caption{display:block}.cine-caption strong{font-size:16px}.cine-caption small{display:block;margin-top:5px}.cine-controls{bottom:22px}.cine-step{right:18px}.cine-label{left:18px}}`;
document.head.appendChild(cinematicStyle);

const screenImages=[
 "https://i.imgur.com/QtuxYWK.jpeg",
 "https://i.imgur.com/xReSL3X.jpeg",
 "https://i.imgur.com/2T3pYsK.jpeg",
 "https://i.imgur.com/3o4hIif.jpeg",
 "https://i.imgur.com/vT8892A.jpeg"
];
const cinematic=document.createElement("section");
cinematic.id="cinematic";cinematic.innerHTML=`
<div class="cine-head"><span>04 / CINEMATIC SHOWCASE</span><h2>VYRA'yı<br><em>yakından hisset.</em></h2><p>Sayfayı kaydırdıkça VYRA'nın ekranları değişsin. Bu bölüm uygulamanın gerçek görüntülerini sinematik bir ürün demosuna dönüştürüyor.</p></div>
<div class="cine-stage"><div class="cine-orb"></div><div class="cine-orb o2"></div><div class="cine-orb o3"></div><div class="cine-label">VYRA / EXPERIENCE</div><div class="cine-step" id="cineStep">01 / 05</div><div class="cine-phone" id="cinePhone"><img id="cineImage" src="${screenImages[0]}" alt="VYRA cinematic preview"></div><div class="cine-caption"><div><strong id="cineTitle">HOME EXPERIENCE</strong><small id="cineSub">Hızlı, sade ve müzik odaklı.</small></div><div class="cine-dots" id="cineDots"></div></div><div class="cine-controls"><button id="cinePrev">← Önceki</button><button id="cineNext">Sonraki →</button></div></div>
<div class="cine-steps" id="cineSteps"></div>`;
document.querySelector(".manifesto")?.before(cinematic);

const cineData=[
 ["HOME EXPERIENCE","Hızlı, sade ve müzik odaklı."],
 ["DISCOVER","Yeni müzikleri keşfet ve akışını koru."],
 ["PLAYER","Müziği merkeze alan oynatma deneyimi."],
 ["LIBRARY","Koleksiyonun, geçmişin ve listelerin."],
 ["PLAYLIST","Kendi müzik akışını kendin oluştur."]
];
let cineIndex=0;
const cineImage=document.getElementById("cineImage"),cineTitle=document.getElementById("cineTitle"),cineSub=document.getElementById("cineSub"),cineStep=document.getElementById("cineStep"),cinePhone=document.getElementById("cinePhone"),cineDots=document.getElementById("cineDots"),cineSteps=document.getElementById("cineSteps");
cineData.forEach((_,i)=>{const d=document.createElement("i");cineDots.appendChild(d);const b=document.createElement("button");b.onclick=()=>setCine(i);cineSteps.appendChild(b)});
function setCine(i){cineIndex=(i+5)%5;cinePhone.style.opacity=".35";cinePhone.style.transform="scale(.96) rotateY("+(cineIndex-2)*3+"deg)";setTimeout(()=>{cineImage.src=screenImages[cineIndex];cineTitle.textContent=cineData[cineIndex][0];cineSub.textContent=cineData[cineIndex][1];cineStep.textContent=String(cineIndex+1).padStart(2,"0")+" / 05";cineDots.querySelectorAll("i").forEach((d,n)=>d.classList.toggle("active",n===cineIndex));cineSteps.querySelectorAll("button").forEach((b,n)=>b.classList.toggle("active",n===cineIndex));cinePhone.style.opacity="1";cinePhone.style.transform="scale(1) rotateY("+(cineIndex-2)*3+"deg)"},130)}
document.getElementById("cinePrev").onclick=()=>setCine(cineIndex-1);document.getElementById("cineNext").onclick=()=>setCine(cineIndex+1);setCine(0);

if(!reduce){const cineObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const r=e.target.getBoundingClientRect(),p=Math.min(1,Math.max(0,(innerHeight-r.top)/(innerHeight+r.height)));if(p>.08){const i=Math.min(4,Math.floor(p*5));if(i!==cineIndex)setCine(i)}}}),{threshold:[.1,.25,.4,.55,.7,.85]});cineObs.observe(cinematic)}

const lightbox=document.createElement("div");lightbox.id="lightbox";lightbox.innerHTML='<button aria-label="Kapat">×</button><img alt="VYRA ekran görüntüsü">';document.body.appendChild(lightbox);const lbImg=lightbox.querySelector("img");document.querySelectorAll(".shot img").forEach(img=>img.addEventListener("click",e=>{e.stopPropagation();lbImg.src=img.src;lightbox.classList.add("open")}));lightbox.addEventListener("click",e=>{if(e.target===lightbox||e.target.tagName==="BUTTON")lightbox.classList.remove("open")});addEventListener("keydown",e=>{if(e.key==="Escape")lightbox.classList.remove("open")});
