const btn=document.getElementById("downloadBtn"),btn2=document.getElementById("downloadBtn2"),version=document.getElementById("version"),menu=document.querySelector(".mobile-menu"),menuBtn=document.querySelector(".menu-btn"),nav=document.querySelector(".nav"),progress=document.getElementById("progress"),heroVisual=document.getElementById("heroVisual");
const api="https://api.github.com/repos/mm2vault/VYRA/releases?per_page=30";
fetch(api,{headers:{Accept:"application/vnd.github+json"}}).then(r=>r.ok?r.json():Promise.reject()).then(rs=>{const latest=rs.filter(x=>!x.draft).sort((a,b)=>new Date(b.published_at||b.created_at)-new Date(a.published_at||a.created_at))[0];if(!latest)throw 0;const apk=(latest.assets||[]).find(x=>x.name.toLowerCase().endsWith(".apk"));version.textContent="Son sürüm: "+latest.tag_name+(latest.prerelease?" · prerelease":"");const url=apk?.browser_download_url||latest.html_url;btn.href=url;btn2.href=url}).catch(()=>{version.textContent="En güncel APK GitHub Releases üzerinde.";btn.href=btn2.href="https://github.com/mm2vault/VYRA/releases"});
menuBtn?.addEventListener("click",()=>{const open=menu.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});menu?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{menu.classList.remove("open");menuBtn?.setAttribute("aria-expanded","false")}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;let targetX=innerWidth/2,targetY=innerHeight*.4,currentX=targetX,currentY=targetY;const pointer=()=>{currentX+=(targetX-currentX)*.12;currentY+=(targetY-currentY)*.12;document.documentElement.style.setProperty("--mx",currentX+"px");document.documentElement.style.setProperty("--my",currentY+"px");if(!reduce)requestAnimationFrame(pointer)};if(!reduce&&matchMedia("(pointer:fine)").matches){addEventListener("pointermove",e=>{targetX=e.clientX;targetY=e.clientY},{passive:true});pointer()}
addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?(scrollY/h)*100:0)+"%";nav.classList.toggle("scrolled",scrollY>18)},{passive:true});
if(!reduce&&matchMedia("(pointer:fine)").matches){const phone=heroVisual?.querySelector(".phone");heroVisual?.addEventListener("pointermove",e=>{const r=heroVisual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;if(phone)phone.style.transform="rotate(4deg) rotateY("+(x*10)+"deg) rotateX("+(-y*10)+"deg) translate("+x*5+"px,"+y*5+"px)";heroVisual.querySelectorAll(".tilt-card").forEach((el,i)=>{el.style.transform="translate3d("+(x*(i+1)*8)+"px,"+(y*(i+1)*8)+"px,0)"})},{passive:true});heroVisual?.addEventListener("pointerleave",()=>{if(phone)phone.style.transform="rotate(4deg)";heroVisual.querySelectorAll(".tilt-card").forEach(el=>el.style.transform="")})}
if(!reduce&&matchMedia("(pointer:fine)").matches){document.querySelectorAll(".magnetic").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform="translate("+(x*.08)+"px,"+(y*.08)+"px)"});el.addEventListener("pointerleave",()=>el.style.transform="")});document.querySelectorAll(".feature.tilt-card").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform="perspective(700px) rotateX("+(-y/r.height*5)+"deg) rotateY("+(x/r.width*5)+"deg) translateY(-3px)"});el.addEventListener("pointerleave",()=>el.style.transform="")})}
const canvas=document.getElementById("particles"),ctx=canvas?.getContext("2d");if(canvas&&!reduce){let W=0,H=0,dpr=Math.min(devicePixelRatio||1,2),dots=[];const resize=()=>{W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(dpr,0,0,dpr,0,0);dots=Array.from({length:Math.min(80,Math.floor(W/15))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.5+.3,v:(Math.random()-.5)*.18,a:Math.random()*.5+.15}))};resize();addEventListener("resize",resize);const draw=()=>{ctx.clearRect(0,0,W,H);for(const p of dots){p.y-=.08;p.x+=p.v;if(p.y<-5)p.y=H+5;if(p.x<-5)p.x=W+5;if(p.x>W+5)p.x=-5;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle="rgba(194,108,255,"+p.a+")";ctx.fill()}requestAnimationFrame(draw)};draw()}
const shots=document.querySelectorAll(".shot");shots.forEach(s=>s.addEventListener("click",()=>{s.classList.toggle("focus");if(s.classList.contains("focus")){s.scrollIntoView({behavior:"smooth",block:"center"})}}));